version: "2.2"
volumes:
  postgres_alfa2:
services:
  postgres_alfa2:
    image: postgres:17.2
    restart: "always"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: '${POSTGRESQL_USER}'
      POSTGRES_PASSWORD: '${POSTGRESQL_PASSWORD}'
      POSTGRES_DB: '${POSTGRESQL_DB}'
    volumes:
      - postgres_alfa2:/var/lib/postgresql/data
  appcloude:
#    image: 'storage:1.0'
    build: .
    ports:
      - '8080:8080'
    depends_on:
      - postgres_alfa2
    environment:
      POSTGRESQL_URL: 'postgres_alfa2'
      POSTGRESQL_PASSWORD: '${POSTGRESQL_USER}'
      POSTGRESQL_USER: '${POSTGRESQL_PASSWORD}'
      POSTGRESQL_DB: '${POSTGRESQL_DB}'